### ISSUE TITLE
Wrong item count

### ISSUE THREAD

**Issue by keplerk** [exile-center/chaos-recipe-overlay#16]
Seems like it isnt counting the weapons right, i have 3 but it just display 1 in the overlay 
and each one of them its ilvl <= 74 and => 60

![image](https://user-images.githubusercontent.com/4659797/94425812-6261a300-0141-11eb-9e9e-7fe36068cf61.png)

**Comment by ddzirt** [comment]
@keplerk have you tried pressing refresh? Do mind if APIs are slow or unresponsive you'd need to wait. Refresh itself is not automatic(not sure about this, need to look through the code first, but maybe @pboutin can answer). At least I am able to get numbers correctly after pressing refresh in a minute or so

**Comment by pboutin** [comment]
one-handed weapons counts as 0.5, since you need 2 to make a chaos recipe. same goes for rings.

**Comment by keplerk** [comment]
> one-handed weapons counts as 0.5, since you need 2 to make a chaos recipe. same goes for rings.

Ohh that's a nice pointer, didnt knew it handled it that way, so shields and one handed weapons are counts as 0.5 then ?

**Comment by pboutin** [comment]
> > one-handed weapons counts as 0.5, since you need 2 to make a chaos recipe. same goes for rings.
> 
> Ohh that's a nice pointer, didnt knew it handled it that way, so shields and one handed weapons are counts as 0.5 then ?

correct :) what you see in the overlay represents the amount of recipes you can do with a given item type

**Comment by keplerk** [comment]
Thanks you both for clarify this point.
